### ISSUE TITLE
[Feature] Ability to move and rotate joints within the VAB/SPH

### ISSUE THREAD

**Issue by ZodiusInfuser** [sirkut/InfernalRobotics#10]
It would be nice to have some limited control of the angle of parts within the VAB/SPH. After seeing TweakScale resize the part and reposition the parts that are attached to it's surfaces, surely it must be possible to adapt this to rotating (or translating) the joint of a part?

**Comment by sirkut** [comment]
Consider this feature request CLOSED! :)
