### ISSUE TITLE
2x Symmetry Fix

### ISSUE THREAD

**Issue by ZodiusInfuser** [sirkut/InfernalRobotics#11]
I was playing around earlier and observed that some tweakables do not apply to all they symmetry groups. For example, put lights in a symmetry mode and the Light On tweakable is separate for each, yet the colour is common across them all.

I wonder whether this could be applied to specific joints we allow (e.g rotatrons), so that the default behaviour is to invert the rotation (since that's useful to most people), but they can then disable it by right clicking on the problem part. Of course this shouldn't be available to all parts, since that may cause clipping.

**Comment by ZodiusInfuser** [comment]
This may be a non-issue now, with the new tweakables. Need to test to confirm the expected behaviour.

**Comment by sirkut** [comment]
Others including myself have noticed that sliders are applied through symmetry mode but toggable tweakables do not. Let me know what you find just to have a confirmation then I will close this.

**Comment by ZodiusInfuser** [comment]
inverting of part rotation direction can now be done via tweakables, on a per part basis, meaning that users can set symmetry up how they want for the 2x case.
