### ISSUE TITLE
Tweakables for IR parts not appearing.

### ISSUE THREAD

**Issue by Phazon8058** [sirkut/InfernalRobotics#18]
In place of where the tweakables should be there is just empty space. This is likely related to the release of KSP 0.24.1.

**Comment by sirkut** [comment]
Did you install TweakScale?

Shawn

On Jul 24, 2014, at 9:59 PM, Phazon8058 notifications@github.com wrote:

In place of where the tweakables should be there is just empty space. This
is likely related to the release of KSP 0.24.1.

—
Reply to this email directly or view it on GitHub
https://github.com/sirkut/InfernalRobotics/issues/18.

**Comment by Phazon8058** [comment]
Yes I did install the latest version of TweakScale and the problem persists.

**Comment by sirkut** [comment]
Download IR 0.18.2 it will fix the empty space you are experiencing. There was an issue with KSPAPIExtensions.
