### ISSUE TITLE
A part was renamed in the update, can't find it

### ISSUE THREAD

**Issue by shrx** [sirkut/InfernalRobotics#19]
I updated my save game to 0.24.2 and new mods, and the game complains that it can't load some ships because the part `IR.StrutDecoupler.Large` is missing. What is the new name for this part, so I can fix the save file?

**Comment by sirkut** [comment]
That is probably from the ActiveStruts work and not part of the Infernal Robotics pack.

http://forum.kerbalspaceprogram.com/threads/85599-WIP-ActiveStruts-Dev-Thread

**Comment by ZodiusInfuser** [comment]
The Strut Decoupler is part of the IR Model Rework, and separate to the ActiveStruts mod: http://forum.kerbalspaceprogram.com/threads/65365-WIP-MSI-s-Infernal-Robotics-Model-Rework-(Pre-Releases-Updated-16-06)
