### ISSUE TITLE
Position tweaking in editor breaks on border conditions

### ISSUE THREAD

**Issue by jdmj** [sirkut/InfernalRobotics#26]
How to reproduce: use any girder, attach a hinge to it. Use either "move" buttons in group editor (<-/->) or position editor gui. Open the hinge a little, close it, repeat until it starts to collapse into itself. See screenshot:
![2014-09-14_00001](https://cloud.githubusercontent.com/assets/5107996/4265110/66ed34f2-3c3f-11e4-9013-8e90e25e08b3.jpg)
Note the "-1" in position editor. Problem appears to exist only in editor, I wasn't able to reproduce it in flight.

**Comment by sirkut** [comment]
Fixed in version 0.19.1 which will be uploaded today.
