### ISSUE TITLE
In VAB/SPH, undo causes IR window to go unresponsive.

### ISSUE THREAD

**Issue by deckblad** [sirkut/InfernalRobotics#27]
In VAB/SPH, after undo, the main IR window with group arrangement goes unresponsive. It basically blanks out when you mouse over. I can fix by saving the and re-loading the craft file.

**Comment by jdmj** [comment]
It also happens if I use SelectRoot to change the root part and then reattach IR part (IR part(s) duplicate in the group editor if I do that).

**Comment by sirkut** [comment]
Known bug with control-z. I have a working fix that I will implement in the next build.

**Comment by sirkut** [comment]
Fix is in place in version 0.19.1 which will be uploaded today.
