### ISSUE TITLE
[Feature] Speed Multiplier per part in VAB/SPH

### ISSUE THREAD

**Issue by ZodiusInfuser** [sirkut/InfernalRobotics#7]
Add the ability to specify a speed multiplier per part in the VAB/SPH. The intention of this is to allow 90 degree, 180 degree and 240 degree rotational parts (such as those in the model rework) to be all reach the end of their travel at the same time whilst controlled as a single group.

**Comment by ZodiusInfuser** [comment]
This is in the newest IR release.

**Comment by sirkut** [comment]
Consider this closed!
