### ISSUE TITLE
[Feature] Dedicated support for free spinning joints

### ISSUE THREAD

**Issue by ZodiusInfuser** [sirkut/InfernalRobotics#8]
Would be nice if free spinning joints were a flag that was set, rather than a fudge of the spring force. Particularly, this would allow checks to be made to have Free joints not appear in the group listing in the VAB/SPH. Also, I would like for joint limits to still be valid, for instance for a free moving hinge.

**Comment by omgnull** [comment]
I would like to block/unblock free servo action axis at runtime for any servo, also return of disabled lock/unlock any action. It's up to @sirkut decision.

**Comment by ZodiusInfuser** [comment]
Certainly that would be nice (provided limits are still adhered to). It would however affect my modelling plans, since some of the designs are specifically for free spinning operation, so would become redundant if the option was available to all.

**Comment by ZodiusInfuser** [comment]
0.16 preview adds a dedicated flag that removes free moving parts from the group list, fulfilling this feature request
