### ISSUE TITLE
Possible removal of the VAB/SPH rotate buttons?

### ISSUE THREAD

**Issue by ZodiusInfuser** [sirkut/InfernalRobotics#9]
I am sure that these buttons had an original purpose, however it is unclear what that is. I know that people like Scott Manley have confused these for intending to actually rotate the joint of the part, rather than the part itself.

I suggest either clarify the functionality of these buttons and make them work as intended if they don't already (axis seems wrong), or remove them from the editor window. Of course for compatibility retain the core function so as not to break old craft.

**Comment by sirkut** [comment]
They still have a purpose. I'm going to close this.

**Comment by ZodiusInfuser** [comment]
In that case how about having a cfg flag so it can be enabled and disabled on certain parts. For instance it just doesn't work right for Rework hinges, as it rotates the part around the center, which isn't where the attachment point is.

**Comment by sirkut** [comment]
Fair enough. I'll add that to the next release. I'll close this issue with
the parameter name that you will need. Thanks for reminding me of your
rework parts and what this does to them.

Shawn

On Sep 24, 2014, at 8:41 AM, ZodiusInfuser notifications@github.com wrote:

In that case how about having a cfg flag so it can be enabled and disabled
on certain parts. For instance it just doesn't work right for Rework
hinges, as it rotates the part around the center, which isn't where the
attachment point is.
